language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
script:
- sbt clean coverage test && sbt "project lib" clean coverage test && sbt coverageAggregate
after_success:
- sbt coveralls && sbt lib/coveralls